name: DependaBot Version update

on:
  pull_request:
    paths: 
    - 'dependabot/*'

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  # Make the group unique, but, distinguish between automatic and manual dispatch
  group: dependabot-${{ github.ref }}
  cancel-in-progress: false

# https://github.com/dependabot/dependabot-core/issues/2737
jobs:
  setup:
    runs-on: ubuntu-20.04
    name: Setup
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependencies') && not(contains(github.event.pull_request.labels.*.name, 'github_actions'))
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check modified files
        id: check_modified
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependencies') && not(contains(github.event.pull_request.labels.*.name, 'github_actions'))
        run: |
          echo "::set-output name=version_modified::$(jq '. | contains(["actions-runner/VERSION"])' ${HOME}/files_modified.json)"

      - name: Increment version and changelog
        if: ${{ !steps.check_modified.outputs.version_modified && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependencies') && not(contains(github.event.pull_request.labels.*.name, 'github_actions')) }}
        run: |
          SEM_VER=$(cat VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.after }})

          # Write files
          echo $SEM_VER > VERSION
          sed -i "12i ## [${SEM_VER}]\n### Changed\n* ${COMMIT_MSG}" CHANGELOG.md

          # Add new git commit
          git add VERSION
          git add CHANGELOG.md
          git config --global user.name "dependabot[bot]"
          git config --global user.email "dependabot[bot]@users.noreply.github.com"
          git commit -m "[Automated] Increment Version"
        working-directory: actions-runner

      - name: Push increment version commit
        if: ${{ !steps.check_modified.outputs.version_modified && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependencies') && not(contains(github.event.pull_request.labels.*.name, 'github_actions')) }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}